namespace CashFlow202.Web.Client.Models;

/// <summary>
/// Representative Cashflow 101/202 profession cards.
/// Values are approximate — players should set their own from their actual profession card.
/// </summary>
public static class Professions
{
    public static readonly List<Profession> All = new()
    {
        new Profession
        {
            Name = "Janitor",
            Salary = 1600,
            Taxes = 196,
            MortgageOrRent = 400,
            SchoolLoanPayment = 0,
            CarPayment = 100,
            CreditCardPayment = 50,
            RetailDebtPayment = 50,
            OtherExpenses = 300,
            Savings = 0,
            SchoolLoanBalance = 0,
            CarLoanBalance = 4500,
            CreditCardBalance = 1000,
            RetailDebtBalance = 1000,
            HomeMortgageBalance = 0,
            NumberOfChildren = 0,
            CostPerChild = 100,
        },
        new Profession
        {
            Name = "Truck Driver",
            Salary = 2500,
            Taxes = 328,
            MortgageOrRent = 500,
            SchoolLoanPayment = 0,
            CarPayment = 100,
            CreditCardPayment = 50,
            RetailDebtPayment = 100,
            OtherExpenses = 450,
            Savings = 200,
            SchoolLoanBalance = 0,
            CarLoanBalance = 5000,
            CreditCardBalance = 1000,
            RetailDebtBalance = 2000,
            HomeMortgageBalance = 0,
            NumberOfChildren = 2,
            CostPerChild = 160,
        },
        new Profession
        {
            Name = "Mechanic",
            Salary = 3000,
            Taxes = 460,
            MortgageOrRent = 600,
            SchoolLoanPayment = 0,
            CarPayment = 100,
            CreditCardPayment = 75,
            RetailDebtPayment = 100,
            OtherExpenses = 500,
            Savings = 0,
            SchoolLoanBalance = 0,
            CarLoanBalance = 5000,
            CreditCardBalance = 1500,
            RetailDebtBalance = 2000,
            HomeMortgageBalance = 0,
            NumberOfChildren = 2,
            CostPerChild = 160,
        },
        new Profession
        {
            Name = "Secretary",
            Salary = 3300,
            Taxes = 560,
            MortgageOrRent = 700,
            SchoolLoanPayment = 0,
            CarPayment = 100,
            CreditCardPayment = 75,
            RetailDebtPayment = 100,
            OtherExpenses = 550,
            Savings = 400,
            SchoolLoanBalance = 0,
            CarLoanBalance = 5000,
            CreditCardBalance = 1500,
            RetailDebtBalance = 2000,
            HomeMortgageBalance = 0,
            NumberOfChildren = 1,
            CostPerChild = 160,
        },
        new Profession
        {
            Name = "Police Officer",
            Salary = 3000,
            Taxes = 368,
            MortgageOrRent = 700,
            SchoolLoanPayment = 0,
            CarPayment = 100,
            CreditCardPayment = 75,
            RetailDebtPayment = 100,
            OtherExpenses = 500,
            Savings = 500,
            SchoolLoanBalance = 0,
            CarLoanBalance = 5000,
            CreditCardBalance = 1500,
            RetailDebtBalance = 2000,
            HomeMortgageBalance = 0,
            NumberOfChildren = 2,
            CostPerChild = 160,
        },
        new Profession
        {
            Name = "Teacher",
            Salary = 3300,
            Taxes = 516,
            MortgageOrRent = 700,
            SchoolLoanPayment = 60,
            CarPayment = 100,
            CreditCardPayment = 75,
            RetailDebtPayment = 75,
            OtherExpenses = 550,
            Savings = 400,
            SchoolLoanBalance = 6000,
            CarLoanBalance = 5000,
            CreditCardBalance = 1500,
            RetailDebtBalance = 1000,
            HomeMortgageBalance = 0,
            NumberOfChildren = 2,
            CostPerChild = 160,
        },
        new Profession
        {
            Name = "Nurse",
            Salary = 4200,
            Taxes = 742,
            MortgageOrRent = 900,
            SchoolLoanPayment = 60,
            CarPayment = 100,
            CreditCardPayment = 100,
            RetailDebtPayment = 100,
            OtherExpenses = 650,
            Savings = 400,
            SchoolLoanBalance = 6000,
            CarLoanBalance = 5000,
            CreditCardBalance = 2000,
            RetailDebtBalance = 2000,
            HomeMortgageBalance = 0,
            NumberOfChildren = 2,
            CostPerChild = 180,
        },
        new Profession
        {
            Name = "Engineer",
            Salary = 4900,
            Taxes = 938,
            MortgageOrRent = 1000,
            SchoolLoanPayment = 100,
            CarPayment = 100,
            CreditCardPayment = 100,
            RetailDebtPayment = 100,
            OtherExpenses = 760,
            Savings = 400,
            SchoolLoanBalance = 12000,
            CarLoanBalance = 5000,
            CreditCardBalance = 3000,
            RetailDebtBalance = 1000,
            HomeMortgageBalance = 0,
            NumberOfChildren = 2,
            CostPerChild = 180,
        },
        new Profession
        {
            Name = "Manager",
            Salary = 4600,
            Taxes = 790,
            MortgageOrRent = 1000,
            SchoolLoanPayment = 100,
            CarPayment = 100,
            CreditCardPayment = 100,
            RetailDebtPayment = 100,
            OtherExpenses = 760,
            Savings = 400,
            SchoolLoanBalance = 12000,
            CarLoanBalance = 5000,
            CreditCardBalance = 3000,
            RetailDebtBalance = 2000,
            HomeMortgageBalance = 0,
            NumberOfChildren = 2,
            CostPerChild = 180,
        },
        new Profession
        {
            Name = "Airline Pilot",
            Salary = 9500,
            Taxes = 2800,
            MortgageOrRent = 1900,
            SchoolLoanPayment = 100,
            CarPayment = 300,
            CreditCardPayment = 150,
            RetailDebtPayment = 150,
            OtherExpenses = 1300,
            Savings = 400,
            SchoolLoanBalance = 12000,
            CarLoanBalance = 16000,
            CreditCardBalance = 5000,
            RetailDebtBalance = 3000,
            HomeMortgageBalance = 202000,
            NumberOfChildren = 3,
            CostPerChild = 380,
        },
        new Profession
        {
            Name = "Lawyer",
            Salary = 7500,
            Taxes = 1850,
            MortgageOrRent = 1900,
            SchoolLoanPayment = 200,
            CarPayment = 200,
            CreditCardPayment = 150,
            RetailDebtPayment = 100,
            OtherExpenses = 1050,
            Savings = 400,
            SchoolLoanBalance = 24000,
            CarLoanBalance = 12000,
            CreditCardBalance = 5000,
            RetailDebtBalance = 3000,
            HomeMortgageBalance = 202000,
            NumberOfChildren = 3,
            CostPerChild = 380,
        },
        new Profession
        {
            Name = "Doctor",
            Salary = 13200,
            Taxes = 3420,
            MortgageOrRent = 1900,
            SchoolLoanPayment = 400,
            CarPayment = 300,
            CreditCardPayment = 150,
            RetailDebtPayment = 150,
            OtherExpenses = 2060,
            Savings = 400,
            SchoolLoanBalance = 48000,
            CarLoanBalance = 16000,
            CreditCardBalance = 5000,
            RetailDebtBalance = 3000,
            HomeMortgageBalance = 202000,
            NumberOfChildren = 3,
            CostPerChild = 380,
        },
        // Custom profession card
        new Profession
        {
            Name = "Custom",
            Salary = 0,
            Taxes = 0,
            MortgageOrRent = 0,
            SchoolLoanPayment = 0,
            CarPayment = 0,
            CreditCardPayment = 0,
            RetailDebtPayment = 0,
            OtherExpenses = 0,
            Savings = 0,
            SchoolLoanBalance = 0,
            CarLoanBalance = 0,
            CreditCardBalance = 0,
            RetailDebtBalance = 0,
            HomeMortgageBalance = 0,
            NumberOfChildren = 0,
            CostPerChild = 0,
        },
    };
}
